### ISSUE TITLE
initial setup, empty page 

### ISSUE THREAD

**Issue by albarron** [HPI-Information-Systems/enno#9]
Hi,

thank you for sharing this nice tool. 

I am trying to setup enno and I think I am missing a step. I did follow the installation instructions in the readme and have the server up and running, but I can only see a (practically) empty page (see attachment). My guess is that the reason is that the data folder is empty and hence no document is available to display? I did not find any documentation about it and I would appreciate any hint on how to proceed.

Thank you in advance! 

![screen shot 2018-05-14 at 10 31 46](https://user-images.githubusercontent.com/5373243/39983994-51555740-5762-11e8-850f-9f6c01d26193.png)

**Comment by TimRepke** [comment]
Hi,
an empty data folder might indeed be the problem... That apparently isn't a case I assumed :D

Do you have any errors or output in the JS console or the terminal you run  the flask backend in?

I should really add some documentation. I tested it on a clean setup with the few commands in the readme and it worked, so I figured everything should be fine.

Please let me know about aforementioned outputs, might help to diagnose. And put some text files in the data folder.

**Comment by albarron** [comment]
Hi,

this is the error:
```
127.0.0.1 - - [14/May/2018 10:18:06] "GET /data/config/asf HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2018 10:18:06] "GET /data/listing/asf HTTP/1.1" 200 -
```
Subfolders config and listing do no exist. I am not sure if they are generated automatically. I see in config-enron.json and config-text.json that two other folders are expected: data/enron and data/asf. The subfolders don't exist either. I created the latter two and saved txt files in there. I still get the empty website and the following error:

```
127.0.0.1 - - [14/May/2018 16:17:31] "GET /data/config/asf HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2018 16:17:31] "GET /data/listing/asf HTTP/1.1" 200 -
```

From line 26 in file enronannotation2neo4j.py and the files in folder wrappers it seems like the input file should be .ann, but I get an error as well with a file with this extension:
```
127.0.0.1 - - [14/May/2018 16:21:59] "GET /static/enno.html HTTP/1.1" 304 -
127.0.0.1 - - [14/May/2018 16:21:59] "GET /static/enno-0.0.1.min.js HTTP/1.1" 304 -
127.0.0.1 - - [14/May/2018 16:21:59] "GET /static/css/enno-0.0.1.min.css HTTP/1.1" 304 -
127.0.0.1 - - [14/May/2018 16:21:59] "GET /data/config/asf HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2018 16:21:59] "GET /data/listing/asf HTTP/1.1" 200 -
```

Thanks!

**Comment by TimRepke** [comment]
Hi @albarron ,
you can safely ignore the files in `scripts/`, just artefacts from other work I was doing.
By default the text config is used. This is an example config that shows how simple txt files can be used as inputs, labels and relations are defined in there as well. All the way in the top you can point it to a folder with text files (https://github.com/TimRepke/enno/blob/master/config-text.json#L6).
The second config is to show an example using a different "wrapper", whereas the wrapper prepares the input (in this case it reads .eml files and only forwards the email text to the frontend). By default it uses the config-text.json (https://github.com/TimRepke/enno/blob/master/enno/__init__.py#L6).

In the config you also give the name of your "datasource" (you could potentially define multiple sources in one config file):
https://github.com/TimRepke/enno/blob/master/config-text.json#L3
That's why you see in in the request log. It is not looking for the folder `/data/config` but rather sends a request to `http://127.0.0.1:5000/data/config`.

The file extension `.ann` is used to mark annotated files (using the json annotation format). Raw text files should not use that extension, otherwise something breaks.

From your logs at least I can't see any issues or errors. Did you get any errors in the JS console in your browser? Are you using Python 3.x?

----

I just did a clean install to test everything is still working fine. Can you try using `http://localhost:5000/static/enno.html` instead of `http://127.0.0.1:5000/static/enno.html`? Othwerwise you get XSS errors from your browser's security policy settings.

**Comment by j-lnaddef** [comment]
@TimRepke 
I guess I have the same problem as albarron, even though I do not understand why he gave the 200 responses as "errors".

Here is my error :
```
GET http://localhost:5000/data/last-sample/asf 500 (INTERNAL SERVER ERROR)
```
And more precisely : 
```
if os.path.isfile(path):
        f = open(path, 'r')
        sample = f.read()
        f.close()
    else:
        return get_listing(options)['flat'][0]['sample']
 
    if os.path.isfile(os.path.join(options['path'], sample)):
        return sample
    return get_listing(options)['flat'][0]
 
IndexError: list index out of range
```

I followed the 
```
pip install Flask, email
npm install
grunt dist
grunt flask
```

but I do not have any `/data/last-sample` folder. Can you please provide a full working example that we can try easily? Thank you in  advance!

**Comment by albarron** [comment]
Hi again,

I just found time to revisit this.
I am running with Python 2. When trying to set  up python 3, I get a dependency error with package email. I guess that is no the issue.

I also tried in a linux box, and I get exactly the same result: an empty page (before it was on OsX).

I indeed can see an error in the browser: 
 
> meh. set source error
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/data/config/asf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
 
Please see a snapshot attached. 
![screen shot 2018-06-11 at 17 00 35](https://user-images.githubusercontent.com/5373243/41237000-2998aea6-6d9b-11e8-93c2-16606097487b.png)

I might be lost here, but this is the only thing I found about CORS: 

https://stackoverflow.com/questions/31276220/cors-header-access-control-allow-origin-missing

Thanks again!

**Comment by TimRepke** [comment]
@albarron please try again with localhost instead of 127.0.0.1 (as mentioned in my previous post). Do you still get that error?

**Comment by TimRepke** [comment]
@j-lnaddef sorry for the late answer. I'm currently at a conference and didn't bring the computer with the project data on it. I'll upload some sample data as soon as I'm back next week.

Quick answer though: `/data/dataset/.last` is not a folder, it's a file. This file will be automatically created.
Your problem actually is that you have no data in the folder. Simply create a folder "asf" under "data" and fill it with .txt files. It should work. You can of course name it any other way, but than you need to adapt the config (which isn't documented yet, I should be doing that :\ )

**Comment by albarron** [comment]
Hi
I am advancing here. As shown in the attachment, I now can see documents in the menu:

![screen shot 2018-06-12 at 17 34 15](https://user-images.githubusercontent.com/5373243/41297035-efd9cdcc-6e66-11e8-818c-983548406c34.png)

Still, when I select one I get the same empty interface. The files are .txt  with plain text. 

This is the error I am getting now:
![screen shot 2018-06-12 at 17 36 32](https://user-images.githubusercontent.com/5373243/41297155-3622024a-6e67-11e8-8809-cca01d93a504.png)

I tried with a .eml file as well, as you mentioned in a previous post. But the result is the same.

**Comment by TimRepke** [comment]
@albarron That is very weird! The variable `e` is only used for events (once to close the selection box with `ESC`, and another time of mouse events to do the actual annotation. Did you click something and then it crashed? Otherwise I don't get it. What browser do you use?
As said before: I'll have access to my computer with the project files on it next week, so I'll upload a MWE

**Comment by TimRepke** [comment]
@albarron @j-lnaddef 
I added example data and wrote a more reasonable readme. I hope that helps!

**Comment by albarron** [comment]
thank you for the update in the documentation! It does help to better understand.

First: Is running `grunt flask` a must or it is either that or `python run.py config-example.json`? I think only the last one is necessary? Because otherwise the second one tells that the port is already taken.

More important. I cloned a fresh copy and followed the instructions. The same menu appears as earlier, but nothing appears when a file is selected. This is what I can see in the terminal log:

`127.0.0.1 - - [25/Jun/2018 18:03:02] "GET /data/sample/txt/text_1.txt HTTP/1.1" 200 -`

This looks weird to me already as, after setting "txt" in `enno/src/enno.html`, I would expect to see `/data/example_txt/`. instead? 

The only place I found contains this is [REST.js](https://github.com/TimRepke/enno/blob/97ee93d3748962f9f41ccb7dafe627bf34fc2826/enno/src/js/REST.js#L111). Not sure if this is how it should be because, at the end of the day, I am getting a 200 message from http (and changing it to `/data/example_txt/` results in a 404).

The Chrome console tells me this when trying to load a file:

> Uncaught (in promise) TypeError: Cannot read property 'substring' of undefined
>    at Enno.getTextAsHtml (enno-0.0.1.min.js:3)
>    at Enno.renderText (enno-0.0.1.min.js:3)
>    at t (enno-0.0.1.min.js:3)

which I guess is derived from [Enno.js](https://github.com/TimRepke/enno/blob/97ee93d3748962f9f41ccb7dafe627bf34fc2826/enno/src/js/Enno.js#L412)?

**Comment by TimRepke** [comment]
> First: Is running grunt flask a must or it is either that or python run.py config-example.json? I think only the last one is necessary? Because otherwise the second one tells that the port is already taken.

Correct. It's pretty much the same. Running `grunt flask` only uses a hardcoded config, whereas the other option allows you to hand over the config as an argument.

I cloned a fresh copy and gave it a try by purely following the readme. No problem for me. I did not get the error and I have no idea how it gets triggered. Could you please use `grunt dev` to generate the static files? This way you don't get a minified version of the javascript. May be easier to debug. Without being able to reproduce the error and running the debugger, it's unfortunately tough to help :\
